version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=solana
      - POSTGRES_PASSWORD=solana
    ports:
      - '5432:5432'
    volumes:
      - ./scripts/create_schema.sql:/docker-entrypoint-initdb.d/scripts/create_schema.sql
