name: Release

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: nightly

jobs:
  release-binaries:
    runs-on: ubuntu-latest
    name: Release binaries
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}

      - name: Build plugin
        run: cargo build --release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/*
